# @name get-prompts
GET http://localhost:3333/prompts

###

# @name upload
POST http://localhost:3333/videos
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="luffy.mp3"
Content-Type: audio/mpeg

< ./luffy.mp3
------WebKitFormBoundary7MA4YWxkTrZu0gW--

###

# @name create-transcription

POST http://localhost:3333/videos/32479fee-f618-414e-a75e-cf82274d1dfa/transcription
Content-Type: application/json

{
    "prompt": "one piece"
}

###

# @name generate-ai-completion

POST http://localhost:3333/ai/complete
Content-Type: application/json

{
    "videoId": "32479fee-f618-414e-a75e-cf82274d1dfa",
    "temperature": 0.5,
    "prompt": "gere um resumo sucinto da transcrição do video a seguir: ''' {transcription} ''' "
}